# Generated by Django 5.2.4 on 2025-10-14 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jogador',
        ),
    ]
