# Generated by Django 5.2.4 on 2025-09-26 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.CharField(max_length=255)),
                ('valor_pontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='desafio.desafio')),
            ],
        ),
    ]
