# Generated by Django 5.2.4 on 2025-10-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jogador', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pontos', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='desafio.desafio')),
            ],
        ),
    ]
