# Generated by Django 5.2.4 on 2025-10-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='factory_type',
            field=models.CharField(blank=True, choices=[('daname', 'DanameManager')], max_length=50, null=True),
        ),
    ]
