# Generated by Django 5.2.4 on 2025-10-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_desafio_factory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
