# Generated by Django 5.2.4 on 2025-10-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0004_alter_jogador_username'),
    ]

    operations = [
    ]
