# Generated by Django 5.2.4 on 2025-10-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0009_auto_20251012_2021'),
    ]

    operations = [
    ]
