# Generated by Django 5.2.4 on 2025-10-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0010_auto_20251012_2029'),
    ]

    operations = [
    ]
