# Generated by Django 5.2.4 on 2025-10-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0013_auto_20251012_2215'),
    ]

    operations = [
    ]
