# Generated by Django 5.2.4 on 2025-10-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0014_auto_20251013_0055'),
    ]

    operations = [
    ]
