# Generated by Django 5.2.4 on 2025-10-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0015_auto_20251013_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='factory_type',
            field=models.CharField(blank=True, choices=[('daname', 'DanameFactory')], max_length=50, null=True),
        ),
    ]
