# Generated by Django 5.2.4 on 2025-10-19 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0016_alter_desafio_factory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('correta', models.BooleanField(blank=True, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='desafio.jogador')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='desafio.questao')),
            ],
            options={
                'unique_together': {('jogador', 'questao')},
            },
        ),
    ]
