# Generated by Django 5.2.4 on 2025-10-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0017_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='pergunta',
            field=models.CharField(max_length=5000),
        ),
    ]
