# Generated by Django 5.2.4 on 2025-10-22 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividade', '0019_presenca_compartilhar_email_alter_atividade_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadePontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=250)),
                ('atividade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='atividade.atividade')),
            ],
        ),
    ]
