# Generated by Django 5.2.4 on 2025-10-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade_pontos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividadepontos',
            old_name='pontos',
            new_name='valor',
        ),
    ]
