# Generated by Django 5.2.4 on 2025-10-12 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_jogador'),
        ('username', '0002_daname_is_available_danamemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='daname',
            name='desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danames', to='desafio.desafio'),
        ),
        migrations.AlterField(
            model_name='danamemanager',
            name='desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_factories', to='desafio.desafio'),
        ),
    ]
