# Generated by Django 5.2.4 on 2025-10-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('username', '0003_daname_desafio_alter_danamemanager_desafio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='daname',
            name='desafio',
        ),
        migrations.RemoveField(
            model_name='danamemanager',
            name='desafio',
        ),
        migrations.AddField(
            model_name='danamemanager',
            name='danames',
            field=models.ManyToManyField(related_name='factories', to='username.daname'),
        ),
    ]
