# Generated by Django 5.2.4 on 2025-10-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('username', '0004_usernamefactory_remove_daname_desafio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsernameFactory',
        ),
        migrations.RemoveField(
            model_name='danamemanager',
            name='user',
        ),
    ]
