# Generated by Django 5.2.4 on 2025-10-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('username', '0005_delete_usernamefactory_remove_danamemanager_user'),
    ]

    operations = [
    ]
