# Generated by Django 5.2.4 on 2025-10-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('username', '0007_auto_20251012_2012'),
    ]

    operations = [
    ]
