# Generated by Django 5.2.4 on 2025-10-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('username', '0012_auto_20251012_2159'),
    ]

    operations = [
    ]
