# Generated by Django 5.2.4 on 2025-10-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('username', '0016_auto_20251013_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanameFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danames', models.ManyToManyField(related_name='factories', to='username.daname')),
            ],
        ),
        migrations.DeleteModel(
            name='DanameManager',
        ),
    ]
