# Generated by Django 5.2.4 on 2025-10-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('palestra', 'Palestra'), ('encerramento', 'Encerramento'), ('conversa', 'Conversa'), ('coffee_break', 'Coffee Break')], max_length=30)),
                ('status', models.CharField(choices=[('provisoria', 'Provisoria'), ('confirmada', 'Confirmada')], default='provisoria', max_length=30)),
                ('comeca_as', models.DateTimeField(unique=True)),
                ('termina_as', models.DateTimeField(unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
            ],
        ),
    ]
