# Generated by Django 5.2.4 on 2025-10-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0009_auto_20251012_2200'),
    ]

    operations = [
    ]
