# Generated by Django 5.2.4 on 2025-10-18 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0012_auto_20251013_0103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='RegistroPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_registro', models.DateTimeField(auto_now_add=True)),
                ('horas', models.PositiveIntegerField(default=1)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_presenca', to='atividade.atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_presenca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horario_registro'],
                'indexes': [models.Index(fields=['usuario', 'atividade', 'horario_registro'], name='atividade_r_usuario_6c0cee_idx')],
            },
        ),
    ]
