# Generated by Django 5.2.4 on 2025-10-19 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0013_atividade_uid_registropresenca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroPresenca',
            new_name='Presenca',
        ),
        migrations.RenameIndex(
            model_name='presenca',
            new_name='atividade_p_usuario_06b001_idx',
            old_name='atividade_r_usuario_6c0cee_idx',
        ),
    ]
