# Generated by Django 5.2.4 on 2025-10-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0015_atividade_titulo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='presenca',
            name='atividade_p_usuario_06b001_idx',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='usuario',
        ),
        migrations.AddField(
            model_name='presenca',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='presenca',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['email', 'atividade', 'horario_registro'], name='atividade_p_email_e203dc_idx'),
        ),
    ]
