# Generated by Django 5.2.4 on 2025-10-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0017_atividade_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='token',
            field=models.CharField(default='', max_length=512, null=True),
        ),
    ]
