# Generated by Django 5.2.4 on 2025-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0018_alter_atividade_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='compartilhar_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='token',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
